steps:
  - id: "testing"
    name: "hashicorp/terraform:1.4.4"
    dir: "."
    entrypoint: "sh"
    args: 
      - "-c"
      - |
        gcloud storage buckets create \
        gs://blog-final-test-cloud-build-made-bucket \
        --project=blog-final-test
        gcloud storage buckets update \
        gs://blog-final-test-cloud-build-made-bucket \
        --versioning

