steps:
  - id: "testing"
    name: "google/cloud-sdk"
    dir: "."
    entrypoint: "sh"
    args: 
      - "-c"
      - |
        gcloud storage buckets create \
        gs://blog-final-test-cloud-build-made-bucket \
        --project=blog-final-test
        gcloud storage buckets update \
        gsutil versioning set on gs://blog-final-test-cloud-build-made-bukcet
